### ISSUE TITLE
Simplify CI by moving some parts under `cargo xtask`

### ISSUE THREAD

**Issue by i386x** [trustification/trustification#466]
Running tasks in our Github CI locally is a bit complex now. By moving some parts of it to `cargo xtask` can both simplify the CI and allow to run CI tasks on a local machine. Adding reporting a code coverage, i.e. how much of the code base is covered with tests, will be also useful.

#### Subtasks

- [ ] Identify and move some parts of Github CI to `cargo xtask` and simplify Github CI accordingly
- [x] Support reporting a code coverage in `cargo xtask test` (#863)
- [ ] ~~Add [trustification](https://github.com/trustification) to [codecov.io](https://codecov.io) (or similar service).~~ We won't a 3rd party service here. We wish to stay on GitHub with our coverage reports and %code-covered badges.

#### Links

* https://doc.rust-lang.org/rustc/instrument-coverage.html
* https://blog.rng0.io/how-to-do-code-coverage-in-rust

**Comment by i386x** [comment]
Just managed how to run GitHub actions locally using `act` in Fedora (`act` does not support `podman` yet). Details in thread https://github.com/nektos/act/issues/303, especially in comments https://github.com/nektos/act/issues/303#issuecomment-882069025 and https://github.com/nektos/act/issues/303#issuecomment-962403508:
```sh
# install act:
sudo dnf copr enable rubemlrm/act-cli
sudo dnf install act-cli

# enable the podman socket
systemctl enable --now --user podman.socket
systemctl start --user podman.socket
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock

# run act
act --bind --container-daemon-socket $XDG_RUNTIME_DIR/podman/podman.sock -W .github/workflows/ci.yaml
```

Output:
```
[CI/formatting] 🚀  Start image=catthehacker/ubuntu:act-22.04
[CI/formatting]   🐳  docker pull image=catthehacker/ubuntu:act-22.04 platform= username= forcePull=true
[CI/formatting]   🐳  docker create image=catthehacker/ubuntu:act-22.04 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[CI/formatting]   🐳  docker run image=catthehacker/ubuntu:act-22.04 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[CI/formatting] ⭐ Run Main actions/checkout@v3
[CI/formatting]   ✅  Success - Main actions/checkout@v3
[CI/formatting] ⭐ Run Main Check formatting
[CI/formatting]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
| /var/run/act/workflow/1: line 2: cargo: command not found
[CI/formatting]   ❌  Failure - Main Check formatting
[CI/formatting] exitcode '127': command not found, please refer to https://github.com/nektos/act/issues/107 for more information
[CI/formatting] 🏁  Job failed
[integration/Integration Tests/integration-tests] 🚀  Start image=catthehacker/ubuntu:act-22.04
[integration/Integration Tests/integration-tests]   🐳  docker pull image=catthehacker/ubuntu:act-22.04 platform= username= forcePull=true
[integration/Integration Tests/integration-tests]   🐳  docker create image=catthehacker/ubuntu:act-22.04 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[integration/Integration Tests/integration-tests]   🐳  docker run image=catthehacker/ubuntu:act-22.04 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[integration/Integration Tests/integration-tests]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[integration/Integration Tests/integration-tests]   ☁  git clone 'https://github.com/arduino/setup-protoc' # ref=v2
[integration/Integration Tests/integration-tests] ⭐ Run Main actions/checkout@v3
[integration/Integration Tests/integration-tests]   ✅  Success - Main actions/checkout@v3
[integration/Integration Tests/integration-tests] ⭐ Run Main actions/cache@v3
[integration/Integration Tests/integration-tests]   🐳  docker cp src=/home/jkucera/.cache/act/actions-cache@v3/ dst=/var/run/act/actions/actions-cache@v3/
[integration/Integration Tests/integration-tests]   🐳  docker exec cmd=[node /var/run/act/actions/actions-cache@v3/dist/restore/index.js] user= workdir=
[integration/Integration Tests/integration-tests]   💬  ::debug::Resolved Keys:
[integration/Integration Tests/integration-tests]   💬  ::debug::["Linux-cargo-aae5d427bcead3805c2fa865bef90ccbf517b3b4d5813c5e4c72f441ca715cab"]
[integration/Integration Tests/integration-tests]   💬  ::debug::Checking zstd --quiet --version
[integration/Integration Tests/integration-tests]   💬  ::debug::1.4.8
[integration/Integration Tests/integration-tests]   💬  ::debug::zstd version: 1.4.8
[integration/Integration Tests/integration-tests]   💬  ::debug::Resource Url: http://10.10.10.176:37729/_apis/artifactcache/cache?keys=Linux-cargo-aae5d427bcead3805c2fa865bef90ccbf517b3b4d5813c5e4c72f441ca715cab&version=83506b414ba87cc01b52a400cfb7ebf233d95a35b89fc19980b90ea45da7b823
[integration/Integration Tests/integration-tests]   💬  ::debug::Failed to delete archive: Error: ENOENT: no such file or directory, unlink ''
| Cache not found for input keys: Linux-cargo-aae5d427bcead3805c2fa865bef90ccbf517b3b4d5813c5e4c72f441ca715cab
[integration/Integration Tests/integration-tests]   ✅  Success - Main actions/cache@v3
[integration/Integration Tests/integration-tests] ⭐ Run Main Install Protoc
[integration/Integration Tests/integration-tests]   🐳  docker cp src=/home/jkucera/.cache/act/arduino-setup-protoc@v2/ dst=/var/run/act/actions/arduino-setup-protoc@v2/
[integration/Integration Tests/integration-tests]   🐳  docker exec cmd=[node /var/run/act/actions/arduino-setup-protoc@v2/dist/index.js] user= workdir=
[integration/Integration Tests/integration-tests]   💬  ::debug::evaluating 5 versions
[integration/Integration Tests/integration-tests]   💬  ::debug::matched: 23.4
| Getting protoc version: v23.4
[integration/Integration Tests/integration-tests]   💬  ::debug::isExplicit: 
[integration/Integration Tests/integration-tests]   💬  ::debug::explicit? false
[integration/Integration Tests/integration-tests]   💬  ::debug::evaluating 0 versions
[integration/Integration Tests/integration-tests]   💬  ::debug::match not found
| Downloading archive: https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-linux-x86_64.zip
[integration/Integration Tests/integration-tests]   💬  ::debug::Downloading https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-linux-x86_64.zip
[integration/Integration Tests/integration-tests]   💬  ::debug::Destination /tmp/2acfda8f-ef4d-4248-bf26-532963ca9ce9
[integration/Integration Tests/integration-tests]   💬  ::debug::download complete
| [command]/usr/bin/unzip -o -q /tmp/2acfda8f-ef4d-4248-bf26-532963ca9ce9
[integration/Integration Tests/integration-tests]   💬  ::debug::Caching tool protoc v23.4 x64
[integration/Integration Tests/integration-tests]   💬  ::debug::source dir: /tmp/22356c26-af78-45e5-a649-53205a280435
[integration/Integration Tests/integration-tests]   💬  ::debug::destination /opt/hostedtoolcache/protoc/v23.4/x64
[integration/Integration Tests/integration-tests]   💬  ::debug::finished caching tool
| Protoc cached under /opt/hostedtoolcache/protoc/v23.4/x64
[integration/Integration Tests/integration-tests]   ✅  Success - Main Install Protoc
[integration/Integration Tests/integration-tests]   ⚙  ::add-path:: /opt/hostedtoolcache/protoc/v23.4/x64/bin
[integration/Integration Tests/integration-tests] ⭐ Run Main Compose
[integration/Integration Tests/integration-tests]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=
| /var/run/act/workflow/3: line 2: docker-compose: command not found
[integration/Integration Tests/integration-tests]   ❌  Failure - Main Compose
[integration/Integration Tests/integration-tests] exitcode '127': command not found, please refer to https://github.com/nektos/act/issues/107 for more information
[integration/Integration Tests/integration-tests] ⭐ Run Main Print logs
[integration/Integration Tests/integration-tests]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/5] user= workdir=
| CONTAINER ID   IMAGE                                                    COMMAND                  CREATED          STATUS                     PORTS      NAMES
| 18ead731697d   quay.io/minio/mc:RELEASE.2023-06-19T19-31-19Z            ""                       40 hours ago     Exited (0) 40 hours ago               compose_createbuckets_1
| 1edc7d4ba398   registry.fedoraproject.org/fedora:latest                 "/bin/bash"              2 months ago     Exited (0) 2 months ago               affectionate_shaw
| 1f5e7ae20c24   quay.io/rhel-devel-tools/rhel-developer-toolbox:latest   "toolbox --log-level…"   3 weeks ago      Exited (143) 2 weeks ago              rhel-developer-toolbox-latest
| 22a4adaf8ee5   registry.fedoraproject.org/fedora:latest                 "/bin/bash"              4 months ago     Exited (0) 4 months ago               festive_haslett
| 22f7d92042c9   registry.fedoraproject.org/fedora:latest                 "/bin/bash"              3 weeks ago      Exited (0) 3 weeks ago                nice_chatelet
| 3a938befa9f6   registry.fedoraproject.org/fedora:latest                 "/bin/bash"              3 weeks ago      Exited (0) 3 weeks ago                infallible_vaughan
| 3cfe097f3c91   localhost/osh-hub:latest                                 "/bin/sh -c /run.sh"     2 months ago     Exited (0) 2 weeks ago     8000/tcp   osh-hub
| 4377e9f5bc83   bitnami/kafka                                            "/opt/bitnami/script…"   40 hours ago     Up 40 hours                9092/tcp   compose_kafka_1
| 4bbc933080cf   registry.fedoraproject.org/fedora:latest                 "/bin/bash"              2 months ago     Exited (0) 2 months ago               nervous_dirac
| 7643c30f773f   registry.fedoraproject.org/fedora:latest                 "bash"                   2 months ago     Exited (0) 2 months ago               flamboyant_rhodes
| 87c93ce58025   quay.io/keycloak/keycloak:20.0.0                         "start-dev"              40 hours ago     Up 40 hours                8080/tcp   compose_keycloak_1
| 8d6608c61834   catthehacker/ubuntu:act-22.04                            ""                       45 seconds ago   Up 44 seconds                         act-CI-formatting-e25923f964ce4c157e22ad7ae90e70116369189c8f75862f4d2ac48a5eb1b045
| 8fd84436f47f   catthehacker/ubuntu:act-22.04                            ""                       42 seconds ago   Up 41 seconds                         act-integration-Integration-Tests-integration-tests-d5c51d28510bc83212499cb8f6c8c325718d16a41cba088d30f4ac522a3002ca
| aece3376ef6d   registry.fedoraproject.org/fedora:latest                 "/bin/bash"              3 weeks ago      Exited (1) 3 weeks ago                eloquent_stonebraker
| bf1cfc74ac93   quay.io/sclorg/postgresql-12-c8s:latest                  "run-postgresql"         2 months ago     Exited (0) 2 weeks ago     5432/tcp   db
| ccdcacba8985   quay.io/minio/minio:RELEASE.2023-06-19T19-52-50Z         "server --console-ad…"   40 hours ago     Up 40 hours                9000/tcp   compose_minio_1
| ed8f243ec819   quay.io/keycloak/keycloak:20.0.0                         "/init-sso/init.sh"      40 hours ago     Exited (0) 40 hours ago               compose_init-keycloak_1
| /var/run/act/workflow/5: line 3: docker-compose: command not found
[integration/Integration Tests/integration-tests]   ❌  Failure - Main Print logs
[integration/Integration Tests/integration-tests] exitcode '127': command not found, please refer to https://github.com/nektos/act/issues/107 for more information
[integration/Integration Tests/integration-tests] 🏁  Job failed
Error: Job 'integration-tests' failed
```
(I am using medium sized docker image to save my disk space and it seems `cargo` and `docker-compose` are not present here)
